ALPINE_VERSION="3.19"
POSTFIX_VERSION="7.2.4"

MAINTAINER="edward.finlayson@btinternet.com"
AUTHORNAME="Edward Finlayson"
AUTHORS="edward.finlayson@btinternet.com"
VERSION="0.1"

SCHEMAVERSION="1.0"
NAME="Technoboggle/postfix-alpine"
DESCRIPTION="Technoboggle Postfix email server on Alpine"
URL="http://technoboggle.com/"
VCS_URL="https://github.com/Technoboggle/postfix-alpine"
VENDOR="WSO2"
BUILD_VERSION="0.1"
BUILD_DATE=""
VCS_REF=""